---
- name: Ensure Wazuh agent directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /tmp/wazuh
    - /var/ossec

- name: Copy Wazuh Linux agent from cache when offline
  copy:
    src: "{{ playbook_dir }}/../cache/wazuh/linux-agent/wazuh-agent_4.7.2-1_amd64.deb"
    dest: /tmp/wazuh/wazuh-agent.deb
  when: offline_mode | default(false)

- name: Install Wazuh Linux agent from cache
  apt:
    deb: /tmp/wazuh/wazuh-agent.deb
    state: present
  when: offline_mode | default(false)

- name: Configure Wazuh agent
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf

- name: Register agent with Wazuh manager
  shell: >
    /var/ossec/bin/agent-auth -m {{ wazuh_server_ip }}
    -G {{ wazuh_agent_group | default('default') }}
    -P {{ wazuh_registration_password }}

- name: Start Wazuh agent service
  systemd:
    name: wazuh-agent
    state: started
    enabled: yes