- name: check SQL Server Manager Studio installer exists
  win_stat:
    path: c:\setup\mssql\SSMS_installer.exe
  register: ssms_installer_file

- name: get the installer
  win_get_url:
      url: 'https://aka.ms/ssmsfullsetup'
      dest: 'c:\setup\mssql\SSMS_installer.exe'
  when: not ssms_installer_file.stat.exists

- name: check SSMS installation already done
  win_stat:
    path: "C:\\Program Files (x86)\\Microsoft SQL Server Management Studio 18"
  register: ssms_installation

- name: Install SSMS
  win_command: c:\setup\mssql\SSMS_installer.exe /install /quiet /norestart
  register: install_ssmss
  when: not ssms_installation.stat.exists

- name: Reboot after install
  win_reboot:
    reboot_timeout: 600
  when: not ssms_installation.stat.exists

- name: Create SSMS install directory
  win_file:
    path: c:\setup\ssms
    state: directory

- name: Copy SSMS installer from cache when offline
  win_copy:
    src: "{{ playbook_dir }}/../cache/sql-server/SSMS-Setup-ENU.exe"
    dest: c:\setup\ssms\SSMS-Setup-ENU.exe
  when: offline_mode | default(false)

- name: Download SSMS installer when not offline
  win_get_url:
    url: "https://go.microsoft.com/fwlink/?linkid=2014306"
    dest: c:\setup\ssms\SSMS-Setup-ENU.exe
  when: not offline_mode | default(false)

- name: Install SSMS
  win_package:
    path: c:\setup\ssms\SSMS-Setup-ENU.exe
    arguments: /install /quiet /norestart
    state: present
    expected_return_code: [0, 3010]
  register: ssms_install

- name: Reboot if required
  win_reboot:
    reboot_timeout: 1200
  when: ssms_install.reboot_required